version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/app
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
      - 9229:9229
    tty: true
    networks:
      - game
  db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_EXPOSE}:${DB_PORT}
    volumes:
      - game_main:/var/lib/postgresql/data
    networks:
      - game
volumes:
  game_main:
networks:
  game:
